### ISSUE TITLE
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonMerge  on AWS LINUX AMI

### ISSUE THREAD

**Issue by suhel2112** [awslabs/amazon-kinesis-agent#169]
Details:
agent files cloned to location: /projects/kinesis_log_analytics/amazon-kinesis-agent

[ec2-user@ip-xyz-31-1-abc projects]$ sudo service aws-kinesis-agent start
Starting aws-kinesis-agent (via systemctl):  Job for aws-kinesis-agent.service failed because the control process exited with error code. See "systemctl status aws-kinesis-agent.service" and "journalctl -xe" for details.
                                                           [FAILED]

Error:
[ec2-user@ip-xyz-31-1-abc projects]$ cat /tmp/aws-kinesis-agent.20190209020910.initlog
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonMerge
        at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:50)
        at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:291)
        at com.amazon.kinesis.streaming.agent.config.Configuration.get(Configuration.java:77)
        at com.amazon.kinesis.streaming.agent.config.Configuration.get(Configuration.java:64)
        at com.amazon.kinesis.streaming.agent.Agent.readConfigurationFile(Agent.java:122)
        at com.amazon.kinesis.streaming.agent.Agent.tryReadConfigurationFile(Agent.java:132)
        at com.amazon.kinesis.streaming.agent.Agent.main(Agent.java:58)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonMerge
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

But i do see the following jars mentioned in the pom file.

 <dependency>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-annotations</artifactId>
          <version>2.6.3</version>
        </dependency>
        <dependency>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-core</artifactId>
          <version>2.6.3</version>
        </dependency>
        <dependency>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-databind</artifactId>
          <version>2.9.6</version>

Other checks: (I changed permissions for these files)
[ec2-user@ ... ]$ ls -lhtr /var/run/aws-kinesis*
-rwxrwxrwx 1 root                   root                    5 Feb  9 02:09 /var/run/aws-kinesis-agent.pid

/var/run/aws-kinesis-agent:
total 0
-rwxrwxrwx 1 root root 0 Feb  9 02:09 mutex

[ec2-user@]$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

[ec2-user@.......]$ echo $JAVA_HOME
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.amzn2.x86_64/jre/bin/java

**Comment by suhel2112** [comment]
After trying a few things, i started going through the "setup" file and saw that the following files had different versions.
com.fasterxml.jackson.core jackson-annotations 2.6.3 
com.fasterxml.jackson.core jackson-core 2.6.3 
com.fasterxml.jackson.core jackson-databind 2.9.6

I uninstalled the kinesis agent.

I changed the section of "setup" file that was downloading the pre-listed files and changed the versions of the above mentioned jar files to:
com.fasterxml.jackson.core jackson-annotations 2.9.8
com.fasterxml.jackson.core jackson-core 2.9.8
com.fasterxml.jackson.core jackson-databind 2.9.8

Also made the changes in pom.xml at locations which had the 3 jars as well.

I installed the agent again:
sudo ./setup --install

The agent was successfully installed.
