### ISSUE TITLE
AccessDeniedException in /var/log

### ISSUE THREAD

**Issue by MrAtheist** [awslabs/amazon-kinesis-agent#230]
Trying to follow this [doc](https://docs.aws.amazon.com/streams/latest/dev/writing-with-agents.html) to set up a stream to listen for files under `/var/log`, but getting AccessDeniedException since most of the files are owned by root. Found [this](https://jataws.wordpress.com/2018/01/16/aws-kinesis-accessdeniedexception/) but I'm pretty sure it's just a hack... what would be the proper way of setting up such a stream (in an automated fashion)?

```
{
  "cloudwatch.emitMetrics": true,
  "kinesis.endpoint": "kinesis.us-west-2.amazonaws.com",
  "firehose.endpoint": "",

  "flows": [
    {
      "filePattern": "/var/log/messages*",
      "kinesisStream": "yourkinesisstream",
      "partitionKeyOption": "RANDOM"
    }
  ]
}

```

Relates to https://forums.aws.amazon.com/thread.jspa?threadID=235062

```
$> sudo service aws-kinesis-agent restart
...
java.lang.RuntimeException: java.nio.file.AccessDeniedException: /var/log/messages
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:77)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.AccessDeniedException: /var/log/messages
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at com.amazon.kinesis.streaming.agent.tailing.TrackedFile.open(TrackedFile.java:88)
	at com.amazon.kinesis.streaming.agent.tailing.SourceFileTracker.startTailingNewFile(SourceFileTracker.java:391)
	at com.amazon.kinesis.streaming.agent.tailing.SourceFileTracker.initializeCurrentFile(SourceFileTracker.java:303)
	at com.amazon.kinesis.streaming.agent.tailing.SourceFileTracker.initialize(SourceFileTracker.java:157)
	at com.amazon.kinesis.streaming.agent.tailing.FileTailer.initialize(FileTailer.java:151)
	at com.amazon.kinesis.streaming.agent.tailing.FileTailer.startUp(FileTailer.java:216)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:55)
	... 2 more
aws-kinesis-agent startup                                  [FAILED]
```

**Comment by Leon-Africa** [comment]
My approach was to add the aws-kinesis-agent-user to the sudoers group:

````sudo usermod -aG sudo aws-kinesis-agent-user````
