### ISSUE TITLE
Service fails to connect to checkpoint database on startup

### ISSUE THREAD

**Issue by MattPennock-CMT** [awslabs/amazon-kinesis-agent#248]
After installation on Ubuntu, the service fails to start. 

To workaround an "access denied" exception I had to create `/var/run/aws-kinesis-agent/checkpoints/` and `chgrp` to `aws-kinesis-agent-user`.

After applying the workaround I see the following:

From `/var/log/aws-kinesis-agent/aws-kinesis-agent.log`:

```
2022-11-08 13:07:45.598-0500  (main) com.amazon.kinesis.streaming.agent.Agent [INFO] Reading configuration from file: /etc/aws-kinesis/agent.json
2022-11-08 13:07:45.600-0500  (main) com.amazon.kinesis.streaming.agent.Agent [INFO] Found 1 configured flow(s)
2022-11-08 13:07:45.611-0500  (main) com.amazon.kinesis.streaming.agent.Agent [INFO] null: Agent will use up to 96 threads for sending data.
2022-11-08 13:07:45.689-0500  (main) com.amazon.kinesis.streaming.agent.Agent [ERROR] Unhandled error.
java.lang.RuntimeException: Failed to create or connect to the checkpoint database.
	at com.amazon.kinesis.streaming.agent.tailing.checkpoints.SQLiteFileCheckpointStore.connect(SQLiteFileCheckpointStore.java:108) ~[AWSKinesisStreamingDataAgent-1.1.jar:?]
	at com.amazon.kinesis.streaming.agent.tailing.checkpoints.SQLiteFileCheckpointStore.<init>(SQLiteFileCheckpointStore.java:69) ~[AWSKinesisStreamingDataAgent-1.1.jar:?]
	at com.amazon.kinesis.streaming.agent.Agent.<init>(Agent.java:190) ~[AWSKinesisStreamingDataAgent-1.1.jar:?]
	at com.amazon.kinesis.streaming.agent.Agent.main(Agent.java:96) [AWSKinesisStreamingDataAgent-1.1.jar:?]
Caused by: java.sql.SQLException: The database has been closed
	at org.sqlite.core.NativeDB.throwex(NativeDB.java:471) ~[sqlite-jdbc-3.20.1.jar:?]
	at org.sqlite.core.NativeDB.errmsg_utf8(Native Method) ~[sqlite-jdbc-3.20.1.jar:?]
	at org.sqlite.core.NativeDB.errmsg(NativeDB.java:137) ~[sqlite-jdbc-3.20.1.jar:?]
	at org.sqlite.core.DB.newSQLException(DB.java:921) ~[sqlite-jdbc-3.20.1.jar:?]
	at org.sqlite.core.DB.throwex(DB.java:886) ~[sqlite-jdbc-3.20.1.jar:?]
	at org.sqlite.core.NativeDB._open_utf8(Native Method) ~[sqlite-jdbc-3.20.1.jar:?]
	at org.sqlite.core.NativeDB._open(NativeDB.java:71) ~[sqlite-jdbc-3.20.1.jar:?]
	at org.sqlite.core.DB.open(DB.java:174) ~[sqlite-jdbc-3.20.1.jar:?]
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220) ~[sqlite-jdbc-3.20.1.jar:?]
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76) ~[sqlite-jdbc-3.20.1.jar:?]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25) ~[sqlite-jdbc-3.20.1.jar:?]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24) ~[sqlite-jdbc-3.20.1.jar:?]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45) ~[sqlite-jdbc-3.20.1.jar:?]
	at org.sqlite.JDBC.createConnection(JDBC.java:114) ~[sqlite-jdbc-3.20.1.jar:?]
	at org.sqlite.JDBC.connect(JDBC.java:88) ~[sqlite-jdbc-3.20.1.jar:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_342]
	at java.sql.DriverManager.getConnection(DriverManager.java:270) ~[?:1.8.0_342]
	at com.amazon.kinesis.streaming.agent.tailing.checkpoints.SQLiteFileCheckpointStore.connect(SQLiteFileCheckpointStore.java:105) ~[AWSKinesisStreamingDataAgent-1.1.jar:?]
	... 3 more
```

Notes:
* Ubuntu 22.04 (jammy)
* x86_64
* Agent build with `./setup --install`
* `java -version` is openjdk version "1.8.0_342"
* `javac -version` is javac 1.8.0_342

Let me know if there is anything else I can provide.

**Comment by rbawaskar** [comment]
Follow the following instructions : https://github.com/awslabs/amazon-kinesis-agent/issues/189#issuecomment-574127311

It solved my issue.
