### ISSUE TITLE
Could not initialize class org.joda.time.chrono.ISOChronology

### ISSUE THREAD

**Issue by diranged** [awslabs/amazon-kinesis-agent#62]
We just discovered a series of hosts that all had the Kinesis agent completely broken, throwing the following errors about being unable to initialize the `org.joda/time/chrono.ISOChronology` class. We're not sure when these started, but restarting Kinesis fixed them.

Any thoughts on what could have caused this?

```
2016-12-14 20:42:02.847+0000 staging-us1-ecs-uswest2-31-i-4f3d5557 (Agent.MetricsEmitter RUNNING) com.amazon.kinesis.streaming.agent.Agent [WARN] Agent: Tailing is 2914.839844 MB
 (3056431517 bytes) behind. There are 8 file(s) newer than current file(s) being tailed.
2016-12-14 20:42:03.706+0000 staging-us1-ecs-uswest2-31-i-4f3d5557 (sender-815608) com.amazon.kinesis.streaming.agent.tailing.AsyncPublisher [ERROR] AsyncPublisher[kinesis:log-pi
peline-eng-syslog:/mnt/log/cron.json*]:RecordBuffer(id=14,records=17,bytes=7857) Retriable send error (java.lang.NoClassDefFoundError: Could not initialize class org.joda.time.ch
rono.ISOChronology). Will retry.
2016-12-14 20:42:04.077+0000 staging-us1-ecs-uswest2-31-i-4f3d5557 (sender-815609) com.amazon.kinesis.streaming.agent.tailing.AsyncPublisher [ERROR] AsyncPublisher[kinesis:log-pi
peline-eng-syslog:/mnt/log/authpriv.json*]:RecordBuffer(id=12,records=34,bytes=15561) Retriable send error (java.lang.NoClassDefFoundError: Could not initialize class org.joda.ti
me.chrono.ISOChronology). Will retry.
2016-12-14 20:42:04.986+0000 staging-us1-ecs-uswest2-31-i-4f3d5557 (sender-815610) com.amazon.kinesis.streaming.agent.tailing.AsyncPublisher [ERROR] AsyncPublisher[kinesis:log-pi
peline-eng-syslog:/mnt/log/mail.json*]:RecordBuffer(id=5,records=5,bytes=2538) Retriable send error (java.lang.NoClassDefFoundError: Could not initialize class org.joda.time.chro
no.ISOChronology). Will retry.
2016-12-14 20:42:06.704+0000 staging-us1-ecs-uswest2-31-i-4f3d5557 (sender-815611) com.amazon.kinesis.streaming.agent.tailing.AsyncPublisher [ERROR] AsyncPublisher[kinesis:log-pi
peline-eng-syslog:/mnt/log/user.json*]:RecordBuffer(id=4,records=1,bytes=458) Retriable send error (java.lang.NoClassDefFoundError: Could not initialize class org.joda.time.chron
o.ISOChronology). Will retry.
2016-12-14 20:42:07.266+0000 staging-us1-ecs-uswest2-31-i-4f3d5557 (cw-metrics-publisher) com.amazon.kinesis.streaming.agent.metrics.CWPublisherRunnable [ERROR] Caught exception 
thrown by metrics Publisher in CWPublisherRunnable
java.lang.NoClassDefFoundError: Could not initialize class org.joda.time.chrono.ISOChronology
	at org.joda.time.DateTimeUtils.getChronology(DateTimeUtils.java:266)
	at org.joda.time.format.DateTimeFormatter.selectChronology(DateTimeFormatter.java:968)
	at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:672)
	at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:560)
	at org.joda.time.format.DateTimeFormatter.print(DateTimeFormatter.java:644)
	at com.amazonaws.auth.internal.AWS4SignerUtils.formatDateStamp(AWS4SignerUtils.java:39)
	at com.amazonaws.auth.internal.AWS4SignerRequestParams.<init>(AWS4SignerRequestParams.java:85)
	at com.amazonaws.auth.AWS4Signer.sign(AWS4Signer.java:184)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:705)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:485)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:306)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:979)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.putMetricData(AmazonCloudWatchClient.java:370)
	at com.amazon.kinesis.streaming.agent.metrics.DefaultCWMetricsPublisher.publishMetrics(Unknown Source)
	at com.amazon.kinesis.streaming.agent.metrics.CWPublisherRunnable.runOnce(Unknown Source)
	at com.amazon.kinesis.streaming.agent.metrics.CWPublisherRunnable.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2016-12-14 20:42:07.587+0000 staging-us1-ecs-uswest2-31-i-4f3d5557 (sender-815612) com.amazon.kinesis.streaming.agent.tailing.AsyncPublisher [ERROR] AsyncPublisher[kinesis:log-pi
peline-eng-syslog:/mnt/log/syslog.json*]:RecordBuffer(id=8,records=1,bytes=1813) Retriable send error (java.lang.NoClassDefFoundError: Could not initialize class org.joda.time.ch
rono.ISOChronology). Will retry.
2016-12-14 20:42:09.187+0000 staging-us1-ecs-uswest2-31-i-4f3d5557 (sender-815613) com.amazon.kinesis.streaming.agent.tailing.AsyncPublisher [ERROR] AsyncPublisher[kinesis:log-pi
peline-eng-events:/mnt/flume/events/*]:RecordBuffer(id=2,records=475,bytes=498287) Retriable send error (java.lang.NoClassDefFoundError: Could not initialize class org.joda.time.
chrono.ISOChronology). Will retry.
```

**Comment by chaochenq** [comment]
Looks like the class does exist in the version used by Agent:

https://github.com/awslabs/amazon-kinesis-agent/blob/master/setup#L118
https://github.com/awslabs/amazon-kinesis-agent/blob/master/pom.xml#L158
http://atetric.com/atetric/javadoc/joda-time/joda-time/2.8.2/org/joda/time/chrono/ISOChronology.html

Did you check if the jar file exists in your class path of those hosts?

**Comment by diranged** [comment]
@chaochenq so they definitely exist because restarting the agent worked just fine. That said, I havn't dug deep enough, but its possible that there is an order-of-operations issue here where the app started up before a file was in place .. but I just don't _think_ thats the case. I'll dig though.

On the flip side, it certainly seems like the app should just die off if it can't load up a critical Java class. Right?

**Comment by diranged** [comment]
@chaochenq so we ran into this again on several of our hosts.. any thoughts here?
