### ISSUE TITLE
is multiline turned on? Unable to parse exception stack traces

### ISSUE THREAD

**Issue by sdolespinsci** [awslabs/amazon-kinesis-agent#97]
Hello,

When created in [regex101](https://regex101.com/r/OMWsIZ/1) I am able to match multiline exception stack trace. With kinesis, it only prints out the first line and ignores the stacktrace.

I have the following dataprocessingoptions:
```
"dataProcessingOptions": [
                        {
                                "optionName": "LOGTOJSON",
                                "logFormat": "COMMONAPACHELOG",
                                "matchPattern":"^(?=\\w)([^\\s]*)\\s+(?=\\d)(.*)(?=\\s+\\[)(?:\\s+\\[)(.*)(?=\\])(?:\\]\\s+)(?=\\w)([^ ]*)(?=:)(?::\\s+)(?=\\w)([\\S\\s]+?)(?=\\n[EID]|\\Z)$",
                                "customFieldNames":["Level","Timestamp","Thread","Class","Message"]
                        }
                ]
```

And the following log events (2).

```
INFO  2017-06-24 03:09:21,812 [Main Server Thread] com.mirth.connect.server.Mirth: Web server running at http://10.0.100.40:8080/ and https://10.0.100.40:8443/
ERROR 2017-06-24 22:24:32,062 [qtp1671273921-27] net.sourceforge.stripes.exception.DefaultExceptionHandler: Unhandled exception in exception handler.
java.lang.NumberFormatException: !hex 110
        at org.eclipse.jetty.util.TypeUtil.convertHexDigit(TypeUtil.java:385)
        at org.eclipse.jetty.util.TypeUtil.parseInt(TypeUtil.java:278)
        at org.eclipse.jetty.http.HttpURI.parse(HttpURI.java:404)
        at org.eclipse.jetty.http.HttpURI.<init>(HttpURI.java:128)
        at org.eclipse.jetty.server.Response.encodeURL(Response.java:440)
        at org.eclipse.jetty.server.Response.encodeRedirectURL(Response.java:477)
        at net.sourceforge.stripes.action.RedirectResolution.execute(RedirectResolution.java:198)
        at net.sourceforge.stripes.controller.DispatcherHelper$7.intercept(DispatcherHelper.java:497)
        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
        at net.sourceforge.stripes.controller.HttpCacheInterceptor.intercept(HttpCacheInterceptor.java:99)
        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
        at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
        at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
        at net.sourceforge.stripes.controller.DispatcherHelper.executeResolution(DispatcherHelper.java:491)
        at net.sourceforge.stripes.controller.DispatcherServlet.executeResolution(DispatcherServlet.java:286)
        at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:170)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1712)
        at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691)
        at com.mirth.connect.server.api.providers.ClickjackingFilter.doFilter(ClickjackingFilter.java:44)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1699)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:534)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by chaochenq** [comment]
Hi, did you specify any "multiLineStartPattern" in agent config? http://docs.aws.amazon.com/streams/latest/dev/writing-with-agents.html#agent-config-settings

By default, agent will treat each new line as a single record for parsing and pattern matching, unless you specify this "multiLineStartPattern", which will treat all the lines in between the pattern as one single record.
